//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationEditor.ValueEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigurationEditor.ValueEdit.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string ButtonCancel_Text {
            get {
                return ResourceManager.GetString("ButtonCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string ButtonOk_Text {
            get {
                return ResourceManager.GetString("ButtonOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert value to specific type.
        /// </summary>
        public static string Can_not_convert_value_to_specific_type {
            get {
                return ResourceManager.GetString("Can_not_convert_value_to_specific_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is not validated.
        /// </summary>
        public static string Key_is_not_validated {
            get {
                return ResourceManager.GetString("Key_is_not_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key was be used.
        /// </summary>
        public static string Key_was_be_used {
            get {
                return ResourceManager.GetString("Key_was_be_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType:.
        /// </summary>
        public static string LabelDataType_Text {
            get {
                return ResourceManager.GetString("LabelDataType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string LabelKey_Text {
            get {
                return ResourceManager.GetString("LabelKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string LabelValue_Text {
            get {
                return ResourceManager.GetString("LabelValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is not exist.
        /// </summary>
        public static string The_key_is_not_exist {
            get {
                return ResourceManager.GetString("The_key_is_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Edit.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
