//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationEditor.Browse {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigurationEditor.Browse.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure delete this section 的本地化字符串。
        /// </summary>
        public static string Are_you_sure_delete_this_section {
            get {
                return ResourceManager.GetString("Are_you_sure_delete_this_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item 的本地化字符串。
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_item {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_this_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE 的本地化字符串。
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Description 的本地化字符串。
        /// </summary>
        public static string ListViewTitle_Description {
            get {
                return ResourceManager.GetString("ListViewTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KEY 的本地化字符串。
        /// </summary>
        public static string ListViewTitle_Key {
            get {
                return ResourceManager.GetString("ListViewTitle_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TYPE 的本地化字符串。
        /// </summary>
        public static string ListViewTitle_Type {
            get {
                return ResourceManager.GetString("ListViewTitle_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VALUE 的本地化字符串。
        /// </summary>
        public static string ListViewTitle_Value {
            get {
                return ResourceManager.GetString("ListViewTitle_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New section... 的本地化字符串。
        /// </summary>
        public static string MenuItem_CreateSection {
            get {
                return ResourceManager.GetString("MenuItem_CreateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New value... 的本地化字符串。
        /// </summary>
        public static string MenuItem_CreateValue {
            get {
                return ResourceManager.GetString("MenuItem_CreateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Delete section 的本地化字符串。
        /// </summary>
        public static string MenuItem_DeleteSection {
            get {
                return ResourceManager.GetString("MenuItem_DeleteSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Delete value 的本地化字符串。
        /// </summary>
        public static string MenuItem_DeleteValue {
            get {
                return ResourceManager.GetString("MenuItem_DeleteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Rename... 的本地化字符串。
        /// </summary>
        public static string MenuItem_EditSection {
            get {
                return ResourceManager.GetString("MenuItem_EditSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit value... 的本地化字符串。
        /// </summary>
        public static string MenuItem_EditValue {
            get {
                return ResourceManager.GetString("MenuItem_EditValue", resourceCulture);
            }
        }
    }
}
